# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bb188a9216a6990b32472d555567e69809eb2c97df10b8b57e618f70373a78ce424ff5acbe04aadd44839bca94c462b231a6b397c85c2cd689db2acfd395d10

test:
  secret_key_base: 26839a4f48db784bd2e7695d3b7e84434fc01f7c75db89eb165caeba02c34141d6be5177163e561bbbc72eb88c73c9e4f8c7579a4adbaf68803183c25860213c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
